In [1]:
import numpy as np

In [4]:
array1 = np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

In [6]:
array2 = np.array([5,6,7,8])
array2

array([5, 6, 7, 8])

In [8]:
np.concatenate([array1, array2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.full((3,5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [17]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [18]:
np.linspace(0, 1, 15)

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [20]:
np.random.randint(0, 10, size = 12)

array([3, 1, 7, 3, 4, 0, 7, 4, 4, 1, 8, 2])

In [28]:
array3 = np.random.randint(0, 100, size = 9, dtype= int).reshape(3,3)
array3

array([[26, 26, 13],
       [31,  2, 73],
       [14, 52, 11]])

In [29]:
array3[array3 > 30]

array([31, 73, 52])

In [30]:
array3 > 30

array([[False, False, False],
       [ True, False,  True],
       [False,  True, False]])